#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    autocomplete_method = "ycm"
    filemanager = "nerdtree"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true 
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_tabline_ft_icon = true 
    enable_statusline_mode = true 

# Enable autocomplete layer
#[[layers]]
#name = 'autocomplete'
#auto_completion_return_key_behavior = "complete"
#auto_completion_tab_key_behavior = "smart"
[[layers]]
name = "fzf"
[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = 'core'
  filetree_show_hidden = true

[[layers]]
  name = "lang#markdown"
  
[[layers]]
  name = "tools"

[[layers]]
  name = "tmux"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lsp"
  filetypes = [
    "java"
  ]
  [layers.override_cmd]
    java = [
    "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx1G",
    "-jar",
    "/home/brown/jdt-language-server/plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar",
    "-configuration",
    "/home/brown/jdt-language-server/config_linux",
    "-data",
    "/home/brown/.cache/javalsp"
    ]
[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#c"
  [layer.clang_std]
    cpp = "c20"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = 'lang#python'
  python_interpreter = '/usr/bin/python3'

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "debug"

[[custom_plugins]]
  repo = "lilydjwg/colorizer"
  on_cmd = ["ColorHighlight", "ColorToggle"]
  merged = false

[[custom_plugins]]
  name = 'junegunn/fzf.vim'
  merged = 0

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
    merged = 0

[[custom_plugins]]
  repo = "rafi/awesome-vim-colorschemes"
  merged = 0

[[custom_plugins]]
  repo = "altercation/vim-colors-solarized"
  merged = 0

[[custom_plugins]]
  repo = "lifepillar/vim-gruvbox8.git"
  merged = 0
[[custom_plugins]]
  repo = "lifepillar/vim-colortemplate"
  merged = 0

[[custom_plugins]]
  repo = "octol/vim-cpp-enhanced-highlight"
  merged = 0

