#!bin/bash
# Load resources
xrdb -merge .Xresources

#tray 
trayer  --tint 0x000000 --edge bottom --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --height 22 &

hsetroot -center ~/1729760.png

# Power manager
if [ -z "$(pgrep mate-power-manager)" ] ; then
    mate-power-manager &
fi
# Taffybar
# if [ -z "$(pgrep taffybar)" ] ; then
#     taffybar &
# fi

# Redshift
if [ -z "$(pgrep redshift)" ] ; then
    redshift &
fi

if [ -z "$(pgrep mate-volume-control-status-icon)" ] ; then
    mate-volume-control-status-icon &
fi

# Autolock
# if [ -z "$(pgrep xautolock)" ] ; then
    # xautolock -time 1 -locker "if ! grep 'RUNNING' /proc/asound/card*/pcm*/sub*/status;then xscreensaver-command -lock; else echo 'Sound on'; fi"
# fi

# Wallpaper
#if [ -z "$(pgrep nitrogen)" ] ; then
#    nitrogen --restore &
#fi

# Screensaver
if [ -z "$(pgrep xscreensaver)" ] ; then
    xscreensaver -no-splash &
fi

# Bluetooth
if [ -x /usr/bin/blueman-applet ] ; then
   blueman-applet &
fi

# compton
if [ -z "$(pgrep compton)" ] ; then
    compton -b &
fi

# Network Applet
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet &
fi

# Google Drive
#if [ -z "$(pgrep insync)" ] ; then
#    insync start &
#fi
# xbindkeys
xbindkeys
exec xmonad
