#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh --cuts
wmname LG3D &
#Startup App
# compton
if [ -z "$(pgrep picom)" ] ; then
    picom --experimental-backends -b &
fi

# Redshift
if [ -z "$(pgrep redshift)" ] ; then
    redshift &
fi

if [ -z "$(pgrep synapse)" ] ; then
    synapse -c &
fi




bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2 
bspc config window_gap           11 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config active_border_color  "#88ff00"
bspc config normal_border_color  "#1E1E1E"
bspc config focused_border_color "#FF6347"
bspc config bottom_padding       20 
bspc config left_padding         0 
bspc config right_padding        0
bspc config top_padding          20 
bspc config ignore_ewmh_focus    false
bspc config click_to_focus       true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier     mod1 
bspc config pointer_action1 none
bspc config pointer_action2 resize_corner
bspc config pointer_action3 move

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Mate-terminal desktop='^2' follow=on
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a Caja desktop='^3' follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a okular desktop='^6' follow=on
bspc rule -a jetbrains-idea desktop='^4'
bspc rule -a jetbrains-pycharm desktop='^4'
bspc rule -a jetbrains-datagrip desktop='^4'
bspc rule -a VSCodium desktop='^4'
